---
mec_net:
  num_simple_edges: 1
  num_leaf_spine_edges: 15
  num_three_tier_edges: 0

simple_edge:
  machine_profile:
    cpu: 256
    memory: 10
    disk: 10

leaf_spine_edge:
  num_spines: 2
  num_leaves: 4
  num_fanout: 2
  machine_profile:
    cpu: 10
    memory: 0.5
    disk: 0.5

mec_topology:
  abilene:
    num_nodes: 11
    topo_file: graph/Abilene1.gml
  kreonet:
    num_nodes: 13
    topo_file: graph/Kreonet1.gml
  edgenet:
    num_nodes: 16
    topo_file: graph/Edgenet.gml
